import { Geist, Geist_Mono } from "next/font/google";
import { Header } from "@/view/ui/Header";
import "./globals.css";
import { ProductsContextProvider } from "@/store/product.provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ProductsContextProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} `}
        >
          <Header />
          {children}
        </body>
      </ProductsContextProvider>
    </html>
  );
}
